---
title: 学术期刊编辑与审稿人入门
author: 于淼
date: 2023-03-18
output:
  markdown::html_format:
    meta:
      css: [default, slides]
      js: [slides]
---

## 自我介绍

- 2010 年本科毕业于山东大学

- 2016 年博士延期毕业于中科院某所

- 2016 - 2018 加拿大滑铁卢大学遛鹅

- 2018 - 2022 美国纽约西奈山医学院抗疫

- 2022 - 至今 美国杰克森实验室捕鼠

## 从投胎到投稿

- 一作11篇 🆚 一稿七拒
        
        - 没有人天生会写论文
        - 投稿存在运气成分
        - 职业规划
        
- 英文表述
        
        - ChatGPT
        - 内容为王

- 售后服务
        
        - 发表跟一辈子
        - 引用>>影响因子

## 学术出版现状

- 开放科学 FAIR

        - Findable Accessible Interoperable Reusable

- 向作者收费，向读者免费

- 期刊矩阵

- 开放审稿/互动式审稿

## 学术编辑与职业编辑

- 学术编辑是兼职，大多数无薪，效率~~低~~

- 职业编辑是专职，博士就业好方向，效率高

- 学术编辑有荣誉属性

- 职业编辑普遍懂推广

## 问题期刊特征

- 年发文量

- 编辑数目

- 论文类型

- 收费合理

- 喜欢宣传ISSN与自己计算的影响因子

## 从投稿到审稿

- 博士阶段0审稿

- 博后阶段-青椒审稿主力

- 审稿属于终身（不付费）学习
        
        - 费曼学习法
        
## 审稿格式

- 第一段

        - 中心思想
        - 核心故事/亮点
        - 定性评价
        
- 第二段

        - 主要问题
        - 伤筋动骨级别
        
- 第三段

        - 次要问题：错别字/语法/表述
        - 按行号来
        
## 审稿注意事项

- 尽快，将心比心

- 是否值得发表
        
        - 值：提改进意见
        - 不值：直接拒，不浪费时间
        
- 不要夹带私货

- 留好记录 ORCID

## 编辑视角

- 推荐审稿人最多选一个

- 审稿人不是校稿编辑，不需要折腾格式

- 审稿人有系统记录（平均审稿时间/打分/黑名单/拒绝审稿率）

## 从审稿到编委

- 审稿人可以自荐，但基本无效

- 出版集团可注册成为带关键词审稿人，可能被系统自动推荐

- 带英风格的编辑

- 树立自己关键词

- 年度审稿人奖

## 从编委到编辑

- 特刊

- 太平天国式副主编

- 副高职称或博导

- 结仇结怨

- 了解前沿

## 利益冲突

- 3-5年合作过文章/项目

- 竞争关系

- 第一时间报告

## 拒稿后反驳

- 个人体会成功率0

- 不浪费时间

- 不要尝试重投换编辑（有查重）

## 总结

- 没有捷径

- 个人学术品牌

- 顺应时代
        
        - 机器审稿？
        - 开放科学

## 谢谢

- yufree@live.cn

- Q&A
